api_platform:
    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header
    defaults:
        pagination_client_items_per_page: true
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage